# Supported: GCC, CLANG, ICX, NVCC
TOOLCHAIN ?= ICX
ENABLE_OPENMP ?= true
ENABLE_LIKWID ?= false

#Feature options
OPTIONS  =  -DSIZE=1250000000ull
OPTIONS +=  -DNTIMES=100
OPTIONS +=  -DARRAY_ALIGNMENT=64
#OPTIONS +=  -DVERBOSE_AFFINITY
#OPTIONS +=  -DVERBOSE_DATASIZE
#OPTIONS +=  -DVERBOSE_TIMER
#OPTIONS +=  -DAVX512_INTRINSICS
