# Supported: GCC, CLANG, ICX, NVCC
TOOLCHAIN ?= GCC
ENABLE_OPENMP ?= true
ENABLE_LIKWID ?= false

#Feature options
OPTIONS  =  -DSIZE=1200000000ull
OPTIONS +=  -DNTIMES=2000
OPTIONS +=  -DARRAY_ALIGNMENT=64
#OPTIONS +=  -DVERBOSE_AFFINITY
#OPTIONS +=  -DVERBOSE_DATASIZE
#OPTIONS +=  -DVERBOSE_TIMER
OPTIONS += -DAVX512_INTRINSICS=1
